### PR TITLE
fix: remove custom auth

### LINKED ISSUE #72: Implement authentication with adonisjs/auth
- Use mongodb-model driver: https://github.com/zakodium/adonis-mongodb#using-with-the-authentication-provider
- Login the user with `ctx.auth.login(user)` for all methods
- Add a field to the session that contains the login method that was used. Let's call it `mylims.auth.method`. (We'll use it for custom logout hooks and/or to indicate that information in the API)
- There should no longer be the need for our custom AuthManager

### PR DESCRIPTION
**Pull request by Xstoudi**

### CODE REVIEW

File: app/Controllers/Http/AuthController.ts [hunk 1]
```diff
@@ -1,24 +1,36 @@
...
+    }
+
+    await auth.login(user);
     return response.ok({ email, role: auth.user?.role });
   }
 
   public async myself({ session, response }: HttpContextContract) {
-    const internalUserId = session.get('internal_user');
+    const internalUserId = session.get('auth_web');
     const user = await User.findById(new ObjectId(internalUserId));
```
Comment (targos) [inline app/Controllers/Http/AuthController.ts]: use `ctx.auth.user`

Comment (targos) [reply app/Controllers/Http/AuthController.ts]: with the SilentAuth middleware
